#pragma once

#define MAX_WORD_LENGTH 32

#define MAX_FILE_NAME_LENGTH 128

#define DEFAULT_NAME "Unknown"

#define MAX_DIAGNOSIS_LENGTH 64

#define DIAGNOSIS_ARRAY_INITIAL_SIZE 20

#define DIAGNOSIS_ARRAY_FACTOR 2

#define DYNAMIC_ARRAY_FACTOR 2

#define BASE_MEDICAL_WORKERS_LIST_FILE_NAME "MedicalWorkersList"

#define BASE_DIAGNOSIS_ARRAY_FILE_NAME "DiagnosisArray"

#define INITIAL_HOSPITAL_UNITS_AMOUNT 5

#define INITIAL_MEDICAL_WORKERS_AMOUNT 10

#define INITIAL_DIAGNOSIS_DATABASE_SIZE 40

#define MAX_HOSPITAL_NAME_LENGTH 64

#define MAX_HOSPITAL_UNIT_NAME_LENGTH 64

#define DEFAULT_EXTERNAL_DATA_FILE_NAME "data.txt"

#define TXT ".txt"

#define INNER_DIRECTORY "//"

#define DEFAULT_UNIT_DIRECTORIES_FILE_NAME "unit_directories"

#define DEFAULT_MEDICAL_WORKERS_FILE_NAME "medical_workers"

#define DEFAULT_DIAGNOSIS_DATABASE_FILE_NAME "diagnosis_database"

#define DEFAULT_PATIENTS_FILE_NAME "patients"

#define MAX_POST_LENGTH 64

#define MAX_SPECIALITY_LENGTH 64

#define MAX_PRESCRIPTION_LENGTH 32

#define DEFAULT_HOUSE_NUMBER 0

#define MAX_ADMISSION_PERIOD 5

#define MAX_ADDRESS_LENGTH 32

#define EXIT_KEY '0'